"""
Auto-generated Cocotb testbench for: alu
Generated by Volta Testbench Generator
"""

import cocotb
from cocotb.triggers import Timer


@cocotb.test()
async def test_add_3_plus_5(dut):
    """3 + 5 = 8"""

    dut.a.value = 3
    dut.b.value = 5
    dut.op.value = 0
    await Timer(2, units="ns")

    assert dut.result.value == 8, \
        f"FAIL add_3_plus_5: result = {int(dut.result.value)}, expected 8"
    assert dut.carry_out.value == 0, \
        f"FAIL add_3_plus_5: carry_out = {int(dut.carry_out.value)}, expected 0"


@cocotb.test()
async def test_add_overflow(dut):
    """15 + 1 overflows"""

    dut.a.value = 15
    dut.b.value = 1
    dut.op.value = 0
    await Timer(2, units="ns")

    assert dut.result.value == 0, \
        f"FAIL add_overflow: result = {int(dut.result.value)}, expected 0"
    assert dut.carry_out.value == 1, \
        f"FAIL add_overflow: carry_out = {int(dut.carry_out.value)}, expected 1"


@cocotb.test()
async def test_sub_7_minus_2(dut):
    """7 - 2 = 5"""

    dut.a.value = 7
    dut.b.value = 2
    dut.op.value = 1
    await Timer(2, units="ns")

    assert dut.result.value == 5, \
        f"FAIL sub_7_minus_2: result = {int(dut.result.value)}, expected 5"


@cocotb.test()
async def test_and_op(dut):
    """1100 AND 1010 = 1000"""

    dut.a.value = 12
    dut.b.value = 10
    dut.op.value = 2
    await Timer(2, units="ns")

    assert dut.result.value == 8, \
        f"FAIL and_op: result = {int(dut.result.value)}, expected 8"


@cocotb.test()
async def test_or_op(dut):
    """1100 OR 1010 = 1110"""

    dut.a.value = 12
    dut.b.value = 10
    dut.op.value = 3
    await Timer(2, units="ns")

    assert dut.result.value == 14, \
        f"FAIL or_op: result = {int(dut.result.value)}, expected 14"


@cocotb.test()
async def test_zero_flag(dut):
    """0 + 0, zero flag high"""

    dut.a.value = 0
    dut.b.value = 0
    dut.op.value = 0
    await Timer(2, units="ns")

    assert dut.result.value == 0, \
        f"FAIL zero_flag: result = {int(dut.result.value)}, expected 0"
    assert dut.zero_flag.value == 1, \
        f"FAIL zero_flag: zero_flag = {int(dut.zero_flag.value)}, expected 1"

