"""
Volta — Testbench Generator
Reads TestVector objects from a DesignSpec and generates Cocotb Python
test files. Each TestVector becomes one async test function that sets
inputs, waits, and checks expected outputs. Runs via Verilator.
"""

import os
import re
import sys
import subprocess
import tempfile
import textwrap
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from schema import (
    DesignSpec,
    ModuleSpec,
    SimulationResult,
    TestVector,
    PortDirection,
)


# ---------------------------------------------------------------------------
# Verilog literal parser
# ---------------------------------------------------------------------------

def parse_verilog_literal(lit: str) -> int:
    """Parse a Verilog numeric literal into a Python int.

    Supports:
        4'd3      → 3
        4'b1100   → 12
        8'hFF     → 255
        2'b00     → 0
        1'b1      → 1
        plain int → int
    """

    lit = lit.strip()

    # sized literal: <width>'<base><digits>
    m = re.match(r"(\d+)'([bdho])([0-9a-fA-F_xXzZ]+)", lit, re.I)
    if m:
        base_char = m.group(2).lower()
        digits = m.group(3).replace("_", "")
        base_map = {"b": 2, "o": 8, "d": 10, "h": 16}
        return int(digits, base_map[base_char])

    # plain integer
    return int(lit, 0)


# ---------------------------------------------------------------------------
# Cocotb test file generator
# ---------------------------------------------------------------------------

def generate_test_file(module: ModuleSpec) -> str:
    """Generate a Cocotb test file from a ModuleSpec's test vectors."""

    input_ports = [p for p in module.ports if p.direction == PortDirection.INPUT]
    output_ports = [p for p in module.ports if p.direction == PortDirection.OUTPUT]

    # Is the design sequential? (has a clock)
    has_clock = any(p.is_clock for p in module.ports)

    lines = []
    lines.append('"""')
    lines.append(f"Auto-generated Cocotb testbench for: {module.name}")
    lines.append(f"Generated by Volta Testbench Generator")
    lines.append('"""')
    lines.append("")
    lines.append("import cocotb")
    lines.append("from cocotb.triggers import Timer")
    if has_clock:
        lines.append("from cocotb.clock import Clock")
    lines.append("")
    lines.append("")

    for tv in module.test_vectors:
        func_name = re.sub(r"[^a-zA-Z0-9_]", "_", tv.name)

        lines.append(f'@cocotb.test()')
        lines.append(f'async def test_{func_name}(dut):')
        lines.append(f'    """{tv.description}"""')
        lines.append(f'')

        if has_clock:
            lines.append(f'    clock = Clock(dut.clk, 10, units="ns")')
            lines.append(f'    cocotb.start_soon(clock.start())')
            lines.append(f'')

        # Drive inputs
        for port_name, value_str in tv.inputs.items():
            val = parse_verilog_literal(value_str)
            lines.append(f'    dut.{port_name}.value = {val}')

        # Wait for combinational logic to settle (or a clock edge)
        if has_clock:
            lines.append(f'    await cocotb.triggers.ClockCycles(dut.clk, 2)')
        else:
            lines.append(f'    await Timer(2, units="ns")')

        lines.append(f'')

        # Check expected outputs
        for port_name, expected_str in tv.expected_outputs.items():
            expected = parse_verilog_literal(expected_str)
            lines.append(f'    assert dut.{port_name}.value == {expected}, \\')
            lines.append(f'        f"FAIL {tv.name}: {port_name} = {{int(dut.{port_name}.value)}}, expected {expected}"')

        lines.append(f'')
        lines.append(f'')

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Makefile generator (Cocotb + Verilator)
# ---------------------------------------------------------------------------

def generate_makefile(
    module_name: str,
    verilog_path: str,
    test_module: str,
) -> str:
    """Generate a Cocotb Makefile for Verilator."""

    return textwrap.dedent(f"""\
        SIM = verilator
        TOPLEVEL_LANG = verilog

        VERILOG_SOURCES = {verilog_path}
        TOPLEVEL = {module_name}
        MODULE = {test_module}

        EXTRA_ARGS += --trace
        EXTRA_ARGS += -Wno-WIDTHTRUNC -Wno-WIDTHEXPAND

        include $(shell cocotb-config --makefiles)/Makefile.sim
    """)


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

def run_testbench(
    spec: DesignSpec,
    verilog_dir: str = "output",
) -> SimulationResult:
    """Generate and run Cocotb testbenches for every module in a DesignSpec.

    Returns a SimulationResult with aggregate pass/fail counts.
    """

    total = 0
    passed = 0
    failed = 0
    failures = []
    full_log = []

    for module in spec.modules:
        if not module.test_vectors:
            full_log.append(f"[{module.name}] No test vectors — skipping")
            continue

        verilog_path = os.path.abspath(
            os.path.join(verilog_dir, f"{module.name}.v")
        )
        if not os.path.exists(verilog_path):
            msg = f"[{module.name}] Verilog not found: {verilog_path}"
            full_log.append(msg)
            failures.append({"module": module.name, "error": msg})
            continue

        # Generate test file
        test_code = generate_test_file(module)
        test_module_name = f"test_{module.name}"

        # Create temp directory for the run (auto-cleanup via context manager)
        with tempfile.TemporaryDirectory(prefix=f"volta_tb_{module.name}_") as work_dir:
            test_path = os.path.join(work_dir, f"{test_module_name}.py")
            with open(test_path, "w") as f:
                f.write(test_code)

            makefile_path = os.path.join(work_dir, "Makefile")
            makefile = generate_makefile(module.name, verilog_path, test_module_name)
            with open(makefile_path, "w") as f:
                f.write(makefile)

            full_log.append(f"[{module.name}] Work dir: {work_dir}")
            full_log.append(f"[{module.name}] Test file: {test_path}")
            full_log.append(f"[{module.name}] Running {len(module.test_vectors)} test(s)...")

            print(f"\n  Running {len(module.test_vectors)} test(s) for: {module.name}")
            print(f"  Work dir: {work_dir}")

            # Run cocotb via make
            try:
                r = subprocess.run(
                    ["make", "-C", work_dir],
                    capture_output=True,
                    text=True,
                    timeout=120,
                    env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
                )
                output = r.stdout + r.stderr
                full_log.append(output)
            except subprocess.TimeoutExpired:
                msg = f"[{module.name}] Simulation timed out after 120s"
                full_log.append(msg)
                total += len(module.test_vectors)
                failed += len(module.test_vectors)
                failures.append({"module": module.name, "error": msg})
                continue

            # Parse cocotb results from XML (must happen before context exits)
            results_xml = os.path.join(work_dir, "results.xml")
            module_total, module_pass, module_fail, module_failures = (
                parse_results_xml(results_xml, module.name)
            )

            total += module_total
            passed += module_pass
            failed += module_fail
            failures.extend(module_failures)

    return SimulationResult(
        success=(failed == 0 and total > 0),
        tests_total=total,
        tests_passed=passed,
        tests_failed=failed,
        failures=failures,
        log="\n".join(full_log),
    )


def parse_results_xml(
    xml_path: str,
    module_name: str,
) -> tuple[int, int, int, list[dict]]:
    """Parse cocotb's JUnit results.xml for pass/fail counts.

    Returns (total, passed, failed, failures).
    """

    if not os.path.exists(xml_path):
        return 0, 0, 0, [{"module": module_name, "error": "results.xml not found"}]

    tree = ET.parse(xml_path)
    root = tree.getroot()

    total = 0
    passed_count = 0
    failed_count = 0
    failure_details = []

    for tc in root.iter("testcase"):
        total += 1
        name = tc.get("name", "unknown")

        # A <failure> child means the test failed
        failure_el = tc.find("failure")
        if failure_el is not None:
            failed_count += 1
            msg = failure_el.get("message", failure_el.text or "")
            print(f"    ✗ {name}: {msg}")
            failure_details.append({
                "module": module_name,
                "test": name,
                "message": msg,
            })
        else:
            passed_count += 1
            print(f"    ✓ {name}")

    return total, passed_count, failed_count, failure_details


# ---------------------------------------------------------------------------
# Standalone helpers — generate without running
# ---------------------------------------------------------------------------

def generate_testbenches(
    spec: DesignSpec,
    output_dir: str = "output",
) -> dict[str, str]:
    """Generate Cocotb test files and return {module_name: test_code}."""

    results = {}
    for module in spec.modules:
        if not module.test_vectors:
            continue
        test_code = generate_test_file(module)
        results[module.name] = test_code

        path = os.path.join(output_dir, f"test_{module.name}.py")
        os.makedirs(output_dir, exist_ok=True)
        with open(path, "w") as f:
            f.write(test_code)
        print(f"  Saved: {path}")

    return results


# ---------------------------------------------------------------------------
# main — demo on EXAMPLE_ALU
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from schema import EXAMPLE_ALU

    print("=" * 60)
    print("  VOLTA — Testbench Generator")
    print("=" * 60)

    alu_module = EXAMPLE_ALU.modules[0]

    # Show what we're generating
    print(f"\n  Design:       {EXAMPLE_ALU.name}")
    print(f"  Module:       {alu_module.name}")
    print(f"  Test vectors: {len(alu_module.test_vectors)}")
    print()

    # Generate and display the test file
    print("--- Generated Cocotb test file ---")
    test_code = generate_test_file(alu_module)
    print(test_code)

    # Save it alongside the Verilog
    output_dir = os.path.join(os.path.dirname(__file__), "..", "output")
    output_dir = os.path.abspath(output_dir)
    print(f"\n--- Saving testbenches ---")
    generate_testbenches(EXAMPLE_ALU, output_dir)

    # Run the tests against output/alu.v
    print(f"\n--- Running testbenches via Verilator ---")
    verilog_dir = output_dir
    result = run_testbench(EXAMPLE_ALU, verilog_dir)

    # Summary
    print(f"\n{'=' * 60}")
    print(f"  SIMULATION RESULTS")
    print(f"{'=' * 60}")
    print(f"  Total:  {result.tests_total}")
    print(f"  Passed: {result.tests_passed}")
    print(f"  Failed: {result.tests_failed}")
    print(f"  Status: {'PASS' if result.success else 'FAIL'}")

    if result.failures:
        print(f"\n  Failures:")
        for f in result.failures:
            print(f"    - {f}")

    print()
